name: research_gpt
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - sqlalchemy
  - psycopg2  # alternative to psycopg2-binary, safer for conda
  - faiss-cpu  # or faiss-gpu if you have CUDA setup
  - pillow
  - python-docx
  - pypdf2
  - pytesseract
  - aiohttp
  - python-multipart
  - pip:
      - fastapi
      - uvicorn[standard]
      - python-jose[cryptography]
      - passlib[bcrypt]
      - python-dotenv
      - aiofiles
      - pdfminer.six
      - boto3
      - mistralai
