"""Initial tables and embeddng updates

Revision ID: fe37a6c55164
Revises: 
Create Date: 2025-05-01 20:29:33.089119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe37a6c55164'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('faiss_path', sa.String(), nullable=True))
    op.add_column('embeddings', sa.Column('chunks_path', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('messages', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_embedding_id', 'messages', ['embedding_id'], unique=False)
    op.create_index('ix_messages_user_id', 'messages', ['user_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index('ix_messages_user_id', table_name='messages')
    op.drop_index('ix_messages_embedding_id', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_column('messages', 'evidence')
    op.drop_column('messages', 'user_id')
    op.drop_column('embeddings', 'chunks_path')
    op.drop_column('embeddings', 'faiss_path')
    # ### end Alembic commands ###
